// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxIbn9DcMzRzPbQMY1pqIdt2dpUbBXfUg',
    appId: '1:14640898186:web:248d07ee17909b55ad8d73',
    messagingSenderId: '14640898186',
    projectId: 'devotion-app-235d9',
    authDomain: 'devotion-app-235d9.firebaseapp.com',
    storageBucket: 'devotion-app-235d9.appspot.com',
    measurementId: 'G-0WG13YMXXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMRR_LBjvGZZK8nY-VJ5TS7v8jOtxNkRc',
    appId: '1:14640898186:android:9243a43bfb01c858ad8d73',
    messagingSenderId: '14640898186',
    projectId: 'devotion-app-235d9',
    storageBucket: 'devotion-app-235d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rI8CjtOYvOTMX_rKDWirXONAyFX5An8',
    appId: '1:14640898186:ios:ac520eef22f8021aad8d73',
    messagingSenderId: '14640898186',
    projectId: 'devotion-app-235d9',
    storageBucket: 'devotion-app-235d9.appspot.com',
    iosClientId:
        '14640898186-0i94mme4h0tv0m4apui9oahf9imgusfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.devoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0rI8CjtOYvOTMX_rKDWirXONAyFX5An8',
    appId: '1:14640898186:ios:ac520eef22f8021aad8d73',
    messagingSenderId: '14640898186',
    projectId: 'devotion-app-235d9',
    storageBucket: 'devotion-app-235d9.appspot.com',
    iosClientId:
        '14640898186-0i94mme4h0tv0m4apui9oahf9imgusfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.devoproject',
  );
}
